# Автоматически сгенерированный файл

from .main import CONFIG_TEMPLATE, CUSTOM_SCRIPT_CODE, DEPLOY_HELPER_CODE, DOC_GENERATOR_CODE, GIT_CLEANUP_CODE, HEALTH_CHECKER_CODE, LINT_AND_FORMAT_CODE, METRIC_REPORT_CODE, README_TEMPLATE, REQUIREMENTS_TEMPLATE, RUN_ALL_CODE, SCAFFOLD_PROJECT_CODE, VERSION_BUMP_CODE, create_structure, main

__all__ = ['main.CONFIG_TEMPLATE', 'main.CUSTOM_SCRIPT_CODE', 'main.DEPLOY_HELPER_CODE', 'main.DOC_GENERATOR_CODE', 'main.GIT_CLEANUP_CODE', 'main.HEALTH_CHECKER_CODE', 'main.LINT_AND_FORMAT_CODE', 'main.METRIC_REPORT_CODE', 'main.README_TEMPLATE', 'main.REQUIREMENTS_TEMPLATE', 'main.RUN_ALL_CODE', 'main.SCAFFOLD_PROJECT_CODE', 'main.VERSION_BUMP_CODE', 'main.create_structure', 'main.main']
